"""Prepdwi_recon

"""
configfile: 'config/config.yml'

include: 'rules/setup.smk'
include: 'rules/anatomical_segmentation.smk'
include: "rules/response_function.smk"
include: 'rules/reconstruction/reconstruction.smk'
include: 'rules/spectral_clustering/spectral_clustering.smk'
include: 'rules/tract_profiles.smk'
include: 'rules/spectral_clustering/qc.smk'
include: 'rules/tests.smk'
#include: "rules/qc.smk"

localrules: all, qc, aggregate_profiles

rule all:
    input:
        expand(
            rules.assign_to_anatomical_tracts.output,
            **inputs.input_lists['preproc_dwi']
        )


rule tractography:
    input:
        expand(
            rules.run_sift2.output.weights,
            **inputs.input_lists['preproc_dwi']
        )

rule reformated:
    input:
        expand(
            rules.reformat_clusters.output,
            **inputs.input_lists['preproc_dwi']
        )

# rule qc:
#     input:
#         expand(
#             bids(root=qc,
#                 datatype='dwi',
#                 suffix='{suffixes}',
#                 **wildcards),
#             **inputs['input_lists']['preproc_dwi'],
#             suffixes=["viewTractography", "viewOdf", "viewInterface"]),
#         expand(
#             rules.create_tractography_png.output,
#             **inputs['input_lists']['preproc_dwi'])
